
import { useState } from 'react';
import { ApplicantData } from '@/utils/applicantSchema';
import { toast } from '@/hooks/use-toast';

export function useGenerateDocument() {
  const [isGenerating, setIsGenerating] = useState(false);
  
  const generateDocument = async (
    templateName: string,
    data: ApplicantData
  ): Promise<void> => {
    setIsGenerating(true);
    
    try {
      // In a real application, this would make a request to a server endpoint
      // that would generate the document using python-docxtpl as shown in the example
      
      // For now, we'll simulate the API call with a delay
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      console.log(`Generating document from ${templateName} template with data:`, data);
      
      // Create file name based on template and applicant name
      const fileName = `${templateName}-${data.applicant_name.replace(/\s+/g, '-')}-${new Date().getTime()}.docx`;
      
      // Create a dummy Word document content (base64 encoded)
      // This is a minimal valid .docx file for demonstration purposes
      const base64Content = "UEsDBBQABgAIAAAAIQCyATgbgAEAAI4FAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslMtOwzAQRfdI/EPkLUrcskAIsXSBWFZQJD7AxJPGqmNbnmlp/56J+xBCoRVqN7ESz9x7MvHNaLJubbaCiMa7UgyLgcjAVV4bNyvF2/R5cCsyJOVqZb2DUmwAxWRyfTWabxwgZdRxpWiI4o4TrBpoFRY+gKM37WOrIsU4I1XNVMwUF6rV12JwI9IaXIZ9oZTzUYo2wY/DphF5PssfcZm8eR9gzuL4DsKsg+CxGMRi2M5r5RKsSBETnDQ5NE5VQqVC1VDFw0j7AEPXDFgLJ3nyGZjrMQjeIRgT5JMO94FwyX3kskNJrDz19303wulf8hP4K0yCYYy/I3O7JpFKJ1XzA3NUcN9OyCeltVtQx4gXWKXy4dRMOb18EsekIrUkCQnL7aQWB8o92Lya1E8JMCtZN0BpESZTBxStyg+7hl0H/XwWJ4rrTywOvGOluhvD4lDVwm0fI7xhOLlPKEw8fGPZgRtK87vYXMLzK3x8MdO/AAAA//8DAFBLAwQUAAYACAAAACEAHpQwJgIBAACMAgAACwAIAl9yZWxzLy5yZWxzIKIEAiigAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKySwWrDMAwA7wX/Q/G9cdnDGKN2L2PQ69b9AJNEM7bBljLWu3//OCuDdYNt2KnSScID7cnk+rrXyRsGih5yNSkKq3TwzbYl+Fhetmd2BiRttMPeByihhAmmk+FoiRNp+MT2waMqLiGVoDl5V0JGcklrdHky5CpvrA6UidvaBI2s3aIN44Tz6Xj8mYGaMdUp+AAVZm9IV1CXdmV45PqD3SfRyr+kv2Srd9ya0NSKwyu3wNs8xJCLTpsLExfJQRPKM3I5DiH5+Pk8+GXG00S7bl71e/4BJjn5DQAA//8DAFBLAwQUAAYACAAAACEANDI2YAMAAABGAgAAGgAIAXhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArFHNSsQwEL4L/ocwd5vuiojs2r2I7FXrDwjJdJttNwkxo/btzWx3QYWFIt0emJn5vpkvpD9+r2xaYsDeUyHzLJcJkveVp6aQXx+v9w8yQXBUgfVEhfxGkI/l7c3wggvA0kLrBiSJICyk48A2a7H3KC3KKI6R6lh7ayEWsTEa5Bya2uzyfJ5p/I1hbxhRD1WmnAdNr5XPy+husMQ+Y+I3McCExR5N9FzJbFOSDgQzGnr/OZrf150l3wqtfHaEwVHt/HOCjI7CXCn2BuPKyIljkbyTGDJWrlESeNoymVHzwkIozqmUfW/hLOTs0TLH/6v+kHnGjCe49n7JJPYHx3/s8gsAAP//AwBQSwMEFAAGAAgAAAAhAFKuqkuNAQAAjQIAAA8AAAB4bC93b3JrYm9vay54bWyMksFuwjAMhu+T9g5V7tQpQyDEKA1o0k7bpEl7gCjxWlHTxMoNhbdfWgbSxjjtFjvf/8d2nDRfB6XJARtXa5bRaBAyAlzUZcX3GX173Y4emHCesbLSmmX0Cw5t8vtzMjeLQxZ1KV1NHBIXJl0V9MypcKkULtiBukEg9mFlbdx5R6qUulFsP4/EXokwDCMpDhX4GyYJnGLRbLAQtVjWQoF36pAK551YE8ngCJNSbnXoMyolIWijuU6d8rBC0daUf94XJV8i+be28VAVXqIqwZNFzdJhNI6dMFaUIIMtiblSBGEolbsF6oNlnVchNZ39Kx4/ptWiVucqOOkOtXFA1V+NTURWFn5zsSesl9z9eTcaCzTrvTsZbWzj++/7V7Azm/2Tcb9hmgvT1IYnZKh236JDGWCbJLwYS05RUvGUTpM0uX6tZPIjZW/RaOONNvKa8vKh5A/eYZjjCw//NpMfAAAA//8DAFBLAwQUAAYACAAAACEA4qYOJhwEAACKCwAAGAAAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbKyV3WrjMBCF7wt9B0v32v6JkxQnOGlJIFBaSN1b1GYcUUsyklyy++wzsp3dbBfoOhfa4mPNaMb6ZuTDcTeUbMvUgBVNHl2GOUu41NwUb3n+evNwccOZQSEaIa2gef7OBv648+M9XHa2sIXQA1NsrMBnMjbISp7bXm+45nJ3odmABSFUbZA3knPBJgwMZMXrhILgBYIQK2GrLuzCSz94BD8+iyXU1Iialsyg7QblUqC0QrevmQ+C12Sf5wURGSkCoXiAM8b+DYt17HVLWD3G0ZgZHWFP6Mb0HoZmPhLGbD4U2/5gcS7UNpaSw/rqapFaGrHT8EH2l9mTI96NvJ38PmKIhSL6ZtVaZia+uNW8/+A67pz0j45zvozpLo9wLxB/RZQojk7uzmKmFncfs6QX3ef5eCaCq3Gql7YRbWXrDfs3dkjHNO7OZDlvoHLVWqy5FGR97z+YKXKvJ6LID0DZgUkxlNM7IkZsayulxVC30hj3TvcEaS1rfgxx9XirGLI9yhTH8Lt01oAwjX1P1ktMbTt4D+9hIDFl9oYCFptKm1jsqZhB684KHEZxpQw+NHhpipnO83CMkCiBrJiKctNbNICcJVsJRZpWngP0I2A+ge4oFd14h2RXwoRltP1f0Ozv/56oE8bR9W+jsRvhF1oKbasfHVpe2j7psKENxKiK7ejwqxvGm/FyadcQcRr7V9JAyXfHpZTiR2tVQ/6TiPnR6v9E65HEEsYlKfHnbOALnbyl/APE3c/mCwAA//8DAFBLAwQUAAYACAAAACEA7OoBB/8CAADEBwAAFQAAAHhsL2NoYXJ0cy9jaGFydDEueG1spFVta5tAEP4r4r5Y3l/KFXtJMVgPW2i+9DttCO7qBIgXl1NOTv97Z3Vt/BGhLOiOO88888zo6sMmzsga5EIZP/QPB4c+Al6aivC5D2/mo7MRQkJRX1FpeOjDBAR6mL5/N9mPPa6M1Z3wawuHPhoBfAKz6sMFCnd4NoM5c+S5gzlbSBZrF/wdGvs5i0jKlAHJCRBUZlnDJ5ObZLjdrsFM7hCZib1DrtMhwhzSf1mp7fRY5DZpq9GJ3+vZ1m8cBGrOGcpL4KUGWXLZMYuQc4U6xLzJCJTmObb5OTZZ5AhisyDt18bZKXchGM1RcFy03ZfxEsw9+AO+KCpQB1qjVZ3IFQh5njHmIwdmyttkZ0c9RoVfkMtOBxH3QtAzr7pcCPmJk3W8x9SounSfl9QnHrYuXWsNiyb6EYbpqnT7YdYwCu1Gs0Fa6bGTGgm7HO3+TC10iwdR0dytR1ZEEKc/8Z7bajX69118G88G4/O5VQCLFXw24p+OY/va5RTW5vBEJ1PqEgcv1IOHGsMr4VMsrScyankdsjkBbS3Rvk08rKJbKx7YxILC1o0EZilfPBNTu0pfm7CHvbyT4OLcbFWq/NO/N9rFl0pWLdkvALyzhp+Cxk6kAlpeqRlQjDy0WrhJp+Wvf92oRfFOSrSVJrLrcahVrvWOdP6LYtAk6pCjGPXqRu3rBcHw2TH4SyX1iLWYmxRc/qtKwHOFWXM/GK7rha0+nHZV4E25HarGV6T9rr6BP2yrf9/QNqwCPzpTQtz3F9h0me72cP4EAAD//wMAUEsDBBQABgAIAAAAIQCYVFYlZAIAAI0EAAATAAAAeGwvdGhlbWUvdGhlbWUxLnhtbKxT247TQBD9hfIPrd/jJD1BK0dZFgm1uwJWsOixnUm8yXrGsucS+A3+gK/hgY/gF1hPbhXFRkVipPTYM2fOnbl49fZhzshvEFIJPvSb53WfAA9FSPlq6N9M5mf3PpHKYB5jJjgM/TVIfxR+fvVyEKQpwUyZdJSnsEkpncY8gSpUN5QtprCn1L3QK+FSiSlISgKQ+FPdIc1a7aYXYcr9gGQ5o185CFMA19SlMRtpYMJslpsy4BTJgXVrV4aETzhbzTiFA566s8FC4YVpHIQHcWTSlAfrst2xjv+vdmoO3F24QOvgi6nFcbmqDYorjVl5qKsaK+G6snxdo+b5vtL6xkCrt6zJ19ZqXc3W9V5Sq77B7WruvJlI1eBmdSNdLZXm9R3eaW8keiu2uNLQbJ21G5u8s0WBOBjawduFV0oX1o0iAXZTvHGDtJnyZhB+W4htyl23Cj6EqQTfX1c26nzvxv0av0f4RO+LvqSl0XqK2OcSfA/9OUzBiCUbX5vZvBFpMetHbVE3egfuWBAJJnbn9crtc8KHfhgrmPESVGm6mDsKv3DRCcR6QW1YbWEJY8Puiuf2gdHoK+Zy+xSr3Vx4lF0LuW3dXrrwr0GnDugrJxd6d4KkGwfunaK5j7l7wuat47n8gdza4zk9nngizvpn7fb52a0rkkQ8sY9Ud1YHmwPAuvBCQ/KBHgg8g8QNUg4hymHs5TMAgezXh/N7Icbw3chMA5FZ8EwtzXRpHWw9qT5W9vf0QC6rHY9SVA6ACyApoh4R6HFruu0Qhxo3UeT3RhWG7qBPQah1qzqnDFcszJEuPUZ+4NChx9DlDsMcFDZFU5jCXGzckw1OBMcLg1eE26vuw1xhucdb7nYb8LXVxfo1fq3hxXJci7fHpINpyXWRIaNf05LdHhNjLZCTT09P+tAPDbZdbZI8UExttwtId4I7wv/2+3qhkZgIdw/uDbJNfwAAAP//AwBQSwMEFAAGAAgAAAAhABwUp6gCAQAAbgEAABgAAAB4bC93b3Jrc2hlZXRzL19yZWxzL3NoZWV0MS54bWwucmVsc4SPzQrCMBCE74LvELZXmzYiImm6iVDvoj6AJts/bBKyK9Xnt1io4MW7DDvDB7Ox3H9kFj3JTq8sC9gkKUjqrLG8l/B+ObidgsikVzRaJyl4UsFhub25gJmmIcVRg1ENMZBoSlhE3CfJ+jSSQGJR6CQieVlLJDZxoTVKGTgnsJtOxvJvB7QbH5FrYyk5L8iLQfQSAsH3N/ZrnrQxdYH4x0dwiJ47rgJ5Axmp1O8AAAD//wMAUEsDBBQABgAIAAAAIQDaXzDawwAAAFABAAAjAAAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHMucmVsc6yQQUvEMBCF74L/IczdjN1DWWS7vYiwV9f1B4Q0nQ3bJCYZrP/eKLiw4MHbMHzzvvfKzfdHGtU7FiZwRm3qBlWA3gQb/GjUr+vj6gYVi/ZWjxCw0RMydVtvV894VM2Q75KJleBZI8cit5FLGFF0ajBgCXlTwrMu5JiL9GPeo7v3YY9dVq+Lih82iJuNxmxnoIykLtplFv78koIHCz/BcjKh4BKjuJBfXKae+JEFJig5LLbgMYqR5er/2HZX7ebicA3hC4O6Qjx7YGftDzmu2Z9evwAAAP//AwBQSwMEFAAGAAgAAAAhAIVdE0h2AQAAxgIAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIySUUvDMBSF3wX/Q8l7m6Qdmwzdixs4mA8DRdzeQnJ3C01Sk7jav3fVrotPvr43J9+599xcTHZH3UQHRNKhyZI0z5IIjQ9lZdZZ8ri8ia+TCNmaslWtDXVJONJksriaXLA500eExWqPFBFDkviFidg8OwTuSBbMDHtQzafwo91hIcMa9RMq1pdN2LP2q1EA4FJrunB9xBzQU82n//4so54CkpYbe76bcYAcHUZk3sd1g0Xaly2FATz01LWGo9rFOs40UmzBavIq7tiqxRA7hR7qc4qjCkZIPn25p+g0esayOVvuchswXQ6i7oIN+yl1k6c/AQ7sq7bLHVbHH6C+wJ5j3/kO7fUOk9TB4Ln/fa+/sPcdK0CmwUJ5A92C026vmjWFvwzkcYQXrlgOHKEkUkR5Ht9m+SSO4zydbU2B0TAPBH8CKAz8hZEN7eKJ0heO9fQxPaNWILrpbIMd3vsAxeIPAAAA//8DAFBLAwQUAAYACAAAACEAlrWt4tEBAAC6AwAAEAAIAWRvY1Byb3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACckkFv2zAMhe8D+h8M3Rs5WVcMgaxiSFf0sGEBkrYXXRXZMxFZEiQ6jv/9KDtI0aPPIvmeHviR3H6pK/EG1lVGZ2Q2SYkATUZWusrIr+eLo1MiHGpd0coYyMgWHNlmHz9sO1NasK7SHoUEnaOgqLoyUntvy5RwUYOmbmIs6JjcGKupj6mtUkvN3ZOtQaZJkqZr4r1FNQasbnB2TeLm3wcvP9tCgrYFKZtG1eQs3tC1Ri//LXGslJzb2yZCORp4B+X7KGDX9aKRT2Bfn5E2VhvoEytAo4oMMl/rCtbBuI3oR2gEICG8IFSLTDJqSA9i59xY0yaQYwWepLgUu6XKZUijaA5KGov44wOes1eNuBmtX8GSFDU4jO1fo04jPUj4xzaCJurvjCNOTaMtT3a57e2LMXdu7Fd+WHD0KhTrhpdY4vAHI/zgRrjhEMRJP+L2yzo3Dy6MGi8cRp67LhQ3VGQkTaaZODk+T+eTi9P0aJoe41fPbYf+HH0JHLdjSuOCt20z6GxPVtr5EPNfDjk+zt8WrRuyzS/OPkf4f2jCoDJ86JaXpK6gOoRHwSjfv+C7vwAAAP//AwBQSwMECgAAAAAAAAAAIQA5PxgKdAIAAHQCAAAWAAAAeGwvZW1iZWRkaW5ncy9pbWFnZS5wbmdodHRwczovL2ltYWdlcy51bnNwbGFzaC5jb20vcGhvdG8tMTQ5MDEzMDA0Njk4NS1iNjBiMTEwYjIyYjI/aXhsaWI9cmItNC4wLjMmcT04MCZ3PTQwMCZmaXQ9bWF4UEsBAi0AFAAGAAgAAAAhALIBOBuAAQAAjgUAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAHpQwJgIBAACMAgAACwAAAAAAAAAAAAAAAAC5AwAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEANDI2YAMAAABGAgAAGgAAAAAAAAAAAAAAAADeBgAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHNQSwECLQAUAAYACAAAACEAUq6qS40BAACNAgAADwAAAAAAAAAAAAAAAAAgCQAAeGwvd29ya2Jvb2sueG1sUEsBAi0AFAAGAAgAAAAhAOKmDiYcBAAAigcAABgAAAAAAAAAAAAAAAAA2woAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbFBLAQItABQABgAIAAAAIQDnHXTYFQMAAEoHAAANAAAAAAAAAAAAAAAAADcPAAB4bC9zdHlsZXMueG1sUEsBAi0AFAAGAAgAAAAhAOzqAQf/AgAAxAcAABUAAAAAAAAAAAAAAAAAeRIAAHhsL2NoYXJ0cy9jaGFydDEueG1sUEsBAi0AFAAGAAgAAAAhAJhUViVkAgAAjQQAABMAAAAAAAAAAAAAAAAArhUAAHhsL3RoZW1lL3RoZW1lMS54bWxQSwECLQAUAAYACAAAACEAHBSnqAIBAABuAQAAGAAAAAAAAAAAAAAAAACGGAAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHNQSwECLQAUAAYACAAAACEA2l8w2sMAAAAUAQAAIwAAAAAAAAAAAAAAAADDGQAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHMucmVsc1BLAQItABQABgAIAAAAIQCFXRNIdgEAAMYCAAARAAAAAAAAAAAAAAAAACkbAABkb2NQcm9wcy9jb3JlLnhtbFBLAQItABQABgAIAAAAIQCWta3i0QEAALoDAAAQAAAAAAAAAAAAAAAAAMEdAABkb2NQcm9wcy9hcHAueG1sUEsBAi0ACgAAAAAAAAAAIQA5PxgKdAIAAHQCAAAWAAAAAAAAAAAAAAAAAPUfAAB4bC9lbWJlZGRpbmdzL2ltYWdlLnBuZ1BLBQYAAAAADQANAEgDAABzIgAAAAA=";
      
      // Create a Blob from the base64 string
      const binaryString = window.atob(base64Content);
      const bytes = new Uint8Array(binaryString.length);
      for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
      const blob = new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
      
      // Create a download URL for the blob
      const url = URL.createObjectURL(blob);
      
      // Create and trigger download
      const element = document.createElement('a');
      element.setAttribute('href', url);
      element.setAttribute('download', fileName);
      element.style.display = 'none';
      document.body.appendChild(element);
      element.click();
      
      // Clean up
      setTimeout(() => {
        document.body.removeChild(element);
        URL.revokeObjectURL(url);
      }, 100);
      
      toast({
        title: "Document generated",
        description: `${fileName} has been downloaded.`,
      });
      
      console.log('Document generated successfully');
      
      return Promise.resolve();
    } catch (error) {
      console.error('Error generating document:', error);
      toast({
        variant: "destructive",
        title: "Generation failed",
        description: "Failed to generate document. Please try again.",
      });
      throw error;
    } finally {
      setIsGenerating(false);
    }
  };
  
  const generateAllDocuments = async (data: ApplicantData): Promise<void> => {
    try {
      setIsGenerating(true);
      
      // Generate Form 1 document
      await generateDocument('form1', data);
      
      // Generate Patent Draft document
      await generateDocument('patent-draft', data);
      
      toast({
        title: "All documents generated",
        description: "Form 1 and Patent Draft have been downloaded.",
      });
    } catch (error) {
      console.error('Error generating all documents:', error);
      toast({
        variant: "destructive",
        title: "Generation failed",
        description: "Failed to generate all documents. Please try again.",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  return { generateDocument, generateAllDocuments, isGenerating };
}
