// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpgklmwtwuamdeqffebi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZ2tsbXd0d3VhbWRlcWZmZWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDMzNDAsImV4cCI6MjA2MTQxOTM0MH0.Rj3v7Ymp9fbsLnGIADa_yFAcCzuhalRpuqbEqsAb8Sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);